const usernames = [
  'Aaran',
  'Aaren',
  'Aarez',
  'Aarman',
  'Aaron',
  'Aaron-James',
  'Aarron',
  'Aaryan',
  'Aaryn',
  'Aayan',
  'Aazaan',
  'Abaan',
  'Abbas',
  'Abdallah',
  'Abdalroof',
  'Abdihakim',
  'Abdirahman',
  'Abdisalam',
  'Abdul',
  'Abdul-Aziz',
  'Abdulbasir',
  'Abdulkadir',
  'Abdulkarem',
  'Smith',
  'Jones',
  'Coollastname',
  'enter_name_here',
  'Ze',
  'Zechariah',
  'Zeek',
  'Zeeshan',
  'Zeid',
  'Zein',
  'Zen',
  'Zendel',
  'Zenith',
  'Zennon',
  'Zeph',
  'Zerah',
  'Zhen',
  'Zhi',
  'Zhong',
  'Zhuo',
  'Zi',
  'Zidane',
  'Zijie',
  'Zinedine',
  'Zion',
  'Zishan',
  'Ziya',
  'Ziyaan',
  'Zohaib',
  'Zohair',
  'Zoubaeir',
  'Zubair',
  'Zubayr',
  'Zuriel',
  'Xander',
  'Jared',
  'Courtney',
  'Gillian',
  'Clark',
  'Jared',
  'Grace',
  'Kelsey',
  'Tamar',
  'Alex',
  'Mark',
  'Tamar',
  'Farish',
  'Sarah',
  'Nathaniel',
  'Parker',
];

const emails = [
"noneme@me.com",
"danzigism@mac.com",
"seebs@att.com",
"muadip@hotmail.com",
"richard@gmail.com",
"epeeist@optonline.com",
"kayvonf@optonline.com",
"scarolan@outlook.com",
"paley@yahoo.com",
"rafasgj@outlook.com",
"heidrich@live.com",
"dexter@gmail.com",
"breegster@aol.com",
"aprakash@live.com",
"hahsler@me.com",
"brickbat@msn.com",
"rtanter@yahoo.com",
"andrewik@optonline.com",
"syncnine@mac.com",
"sequin@live.com",
"lridener@sbcglobal.com",
"hling@gmail.com",
"hmbrand@hotmail.com",
"zwood@aol.com",
"monkeydo@gmail.com",
"evans@sbcglobal.com",
"shawnce@icloud.com",
"hmbrand@sbcglobal.com",
"mcrawfor@hotmail.com",
"specprog@outlook.com",
"rhialto@me.com",
"kawasaki@mac.com"","
"rmcfarla@sbcglobal.com",
"djpig@live.com",
"thassine@outlook.com",
"spadkins@comcast.com",
"blixem@mac.com",
"kildjean@att.com",
"nasor@live.com",
"daveewart@icloud.com",
"zilla@verizon.com",
"crowl@live.com",
"yamla@icloud.com",
"phyruxus@outlook.com",
"gomor@outlook.com",
"trygstad@verizon.com",
"mddallara@mac.com",
"gavinls@verizon.com",
"jeffcovey@gmail.com",
"lridener@msn.com",
"kodeman@comcast.com",
"szymansk@outlook.com",
"esasaki@mac.com",
"dunstan@gmail.com",
"wortmanj@outlook.com",
"afifi@yahoo.com",
"wiseb@sbcglobal.com",
"saridder@me.com",
"engelen@comcast.com",
"jbearp@aol.com",
"jadavis@yahoo.com",
"padme@icloud.com",
"djupedal@hotmail.com",
"attwood@yahoo.com",
"paley@comcast.com",
"bdthomas@yahoo.com",
"jfmulder@sbcglobal.com",
"gfxguy@me.com",
"neonatus@me.com",
"dwendlan@aol.com",
"telbij@att.com",
"gtewari@gmail.com",
"intlprog@msn.com",
]

const appDescriptions = [
  'Decision Tracker',
  'Find My Phone',
  'Learn Piano',
  'Starbase Defender',
  'Tower Defense',
  'Monopoly Money Manager',
  'Movie trailers',
  'Hello world',
  'Stupid Social Media App',
  'Notes',
  'Messages',
  'Email',
  'Compass',
  'Firefox',
  'Running app',
  'Cooking app',
  'Poker',
  'Deliveries',
];

// Get a random item given an array
const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

// Gets a random full name
const getRandomName = () =>
  `${getRandomArrItem(names)} ${getRandomArrItem(names)}`;

// Function to generate random assignments that we can add to student object.
const getRandomAssignments = (int) => {
  const results = [];
  for (let i = 0; i < int; i++) {
    results.push({
      assignmentName: getRandomArrItem(appDescriptions),
      score: Math.floor(Math.random() * (99 - 70 + 1) + 70),
    });
  }
  return results;
};

// Export the functions for use in seed.js
module.exports = { getRandomName, getRandomAssignments };
